extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3dlite_material_006_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_001_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_004_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_003_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_002_lights;
extern u8 castle_grounds_dl_Sprite_0001_rgba32[];
extern u8 castle_grounds_dl_hmc_textures_0B800_ia16_ia8[];
extern u8 castle_grounds_dl_inside_castle_textures_04000_rgba16_rgba16[];
extern u8 castle_grounds_dl_inside_castle_textures_03000_rgba16_rgba16[];
extern u8 castle_grounds_dl_lll_textures_0B800_rgba16_ci8[];
extern u8 castle_grounds_dl_lll_textures_0B800_rgba16_pal_rgba16[];
extern u8 castle_grounds_dl_john_rgba16[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[709];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_1[305];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_5_vtx_0[154];
extern Gfx castle_grounds_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_0[7];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_1[28];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[38];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[6];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_001_mesh_layer_5_vtx_0[772];
extern Gfx castle_grounds_dl_Plane_001_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_005[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_006[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_5[];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_001_mesh_layer_5[];
